### ISSUE TITLE
No systray without enabling session bus socket

### ISSUE THREAD

**Issue by etrnal70** [flathub/io.github.spacingbat3.webcord#1]
There's no systray when launching webcord using default configurations. Enabling session bus socket from Flatseal make it works. Maybe make it as default ?

Using sway (systray using waybar)

**Comment by etrnal70** [comment]
Ahh i see, thank you for the pointer. Some dbus debugging reveals that adding `org.kde.StatusNotifierWatcher` to known session bus in Flatseal is enough to fix this.

**Comment by axtloss** [comment]
Thank you for creating this issue, I will add this extra permission to the new release
