### ISSUE TITLE
Webcord v4.10.2 x64 AppImage SHA256 Mismatch

### ISSUE THREAD

**Issue by j20001970** [flathub/io.github.spacingbat3.webcord#100]
Was wondering why https://github.com/flathub/io.github.spacingbat3.webcord/commit/1b7e3e6e7961b3494c6764fd4f9993978f11d85a is not updated to Flathub yet, and found out sha256 of upstream x64 AppImage had changed from `3997f2b952d405ee2be274496a98085475e7238b7d2f28625821b58513ff9e25` to `21f411c5501904de44c5d33b62ca39dc6047a6a313b4bdb5e8c54118fb5c6cb2`.

Not sure if we should update the checksums, because this normally shouldn't happen.

**Comment by SpidFightFR** [comment]
Should be fixed by https://github.com/flathub/io.github.spacingbat3.webcord/commit/5ad87d8b5bc88da94b807e5eef46833cff0df2fa .
