### ISSUE TITLE
[Bug] Notifications Portal/Permission Missing

### ISSUE THREAD

**Issue by oomfiee** [flathub/io.github.spacingbat3.webcord#2]
So due to missing Permission/Portal in the flatpak webcord cant not send notifications (enabling notifications on webcord and discord  does not fix it) 
Distro: Fedora 36 KDE spin
![image](https://user-images.githubusercontent.com/80048740/177535075-86976928-231a-49f1-be75-85d41954a9ec.png)

**Comment by oomfiee** [comment]
## (discord)
![image](https://user-images.githubusercontent.com/80048740/177544678-e40ba871-1b48-4941-8cc5-fe67e0716732.png)

## (webcord)
![image](https://user-images.githubusercontent.com/80048740/177544779-7c91eab4-5cab-4a26-8454-d90479901e51.png)

**Comment by axtloss** [comment]
This seems to be an issue in webcord itself, though I'll check if there's any way I can fix this from flatpak

**Comment by axtloss** [comment]
I didn't find any way to enable notifications using the flatpak manifest directly, for now you will have to use [flatseal](https://github.com/tchx84/Flatseal) and enable notification support for webcord:
![image](https://user-images.githubusercontent.com/60044824/178113694-f4bcc455-c823-478d-9b68-0a11ce207473.png)
 
this should allow webcord to send notifications.

**Comment by oomfiee** [comment]
reopening issue, tested with flatseal and i am still unable to select the portal (updated the package and everything and still the same thing. maybe i am missing something?)
![image](https://user-images.githubusercontent.com/80048740/179933622-40447468-f898-4444-8ca1-a62b5522d42d.png)

**Comment by oomfiee** [comment]
> it works in kde so it seems that it was missing that

**Comment by axtloss** [comment]
Alright nice to see it working, I'll add these permissions to the manifest, they'll release with the next webcord release
