### ISSUE TITLE
Unable to upload files

### ISSUE THREAD

**Issue by ripper81** [flathub/io.github.spacingbat3.webcord#24]
Hello,

I have noticed that i am not able to upload any files with webchord. The filepicker opens and i can select a file. The file then shows up as an icon in the discord chat.

However i can't do anything with that file. There is no option to download or open it. Webchord also hangs for a while after trying to upload a file.

Systemspecs: Kubuntu 21.10 / KDE Plasma 5.26 Wayland Session.

**Comment by axtloss** [comment]
Could you run webcord from the terminal with `flatpak run io.github.spacingbat3.webcord`, then try to upload an image and send the terminal output here?
It may also be a good idea to check if you're able to reproduce this issue with a non-flatpak webcord package (I believe webcord provides .Deb builds)

**Comment by ripper81** [comment]
I have the Discord App installed as a flatpak on my system too. Uploading files works fine there. However i need screensharing on Wayland, and it does not work with the Discord App.

**Comment by axtloss** [comment]
Have you tested webcord outside of flatpak to see if the same issue happens?
