### ISSUE TITLE
tray icon disapear since last update

### ISSUE THREAD

**Issue by vroger11** [flathub/io.github.spacingbat3.webcord#27]
I don't know why there is this bug. But on manjaro with Kde 2.26.3 the tray icon stopped to appear

**Comment by axtloss** [comment]
Can you check if the tray icon is enabled in the webcord settings?
If it is, can you run webcord from the terminal with `flatpak run io.github.spacingbat3.webcord` and send the log?

**Comment by aleksasiriski** [comment]
[+1](https://github.com/SpacingBat3/WebCord/issues/329#issuecomment-1336423690)

**Comment by aleksasiriski** [comment]
```
[3 zypak-helper] Wait found events, but sd-event found none
Gtk-Message: 15:41:58.940: Failed to load module "canberra-gtk-module"
Gtk-Message: 15:41:58.940: Failed to load module "canberra-gtk-module"
[3:1204/154158.950821:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1204/154158.950849:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[WebSocket] Listening at port 6463.
[UPDATE] Application is up-to-date!
[42:1204/154201.626721:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
[42:1204/154201.627516:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
[42:1204/154201.628366:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
[42:1204/154201.628958:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
[42:1204/154201.629573:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
[42:1204/154201.642691:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
[42:1204/154204.670264:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[42:1204/154204.671511:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
```

**Comment by axtloss** [comment]
Hm nothing really indicates any permission error, could you try using webcord outside of flatpak to see if the issue persists? Webcord offers AppImages which is also what the flatpak uses, so it would be best if you'd try the AppImage

**Comment by valeth** [comment]
I messed around with Flatseal for a bit
When I enable `Session Bus` the tray icon shows up, otherwise it doesn't.

**Comment by axtloss** [comment]
Yes, this would completely open the sandbox to any dbus communication which isn't something I want or even should/can do. So I'll have to track down to which dbus urls it actually talks to

**Comment by valeth** [comment]
Adding `org.kde.StatusNotifierItem-3-1` to the owned bus names seems to do the trick

**Comment by aleksasiriski** [comment]
> I messed around with Flatseal for a bit When I enable `Session Bus` the tray icon shows up, otherwise it doesn't.

That doesn't work for Gnome with Tray Icons: Reloaded

**Comment by axtloss** [comment]
> Adding `org.kde.StatusNotifierItem-3-1` to the owned bus names seems to do the trick.
> 
> Not sure if those names are system specific though, definitely seems to be at least KDE specific.

I don't think it's kde specific, since the StatusNotifierItem-2-1 also worked on gnome with the appindicator extensions

**Comment by aleksasiriski** [comment]
> Adding `org.kde.StatusNotifierItem-3-1` to the owned bus names seems to do the trick.
> 
> Not sure if those names are system specific though, definitely seems to be at least KDE specific.

With `AppIndicator and KStatusNotifierItem Rupport` it shows up briefly and then disappears. `Tray Icons: Reloaded` doesn't work, yet it worked on previous version.

**Comment by vroger11** [comment]
> Adding `org.kde.StatusNotifierItem-3-1` to the owned bus names seems to do the trick.
> 
> Not sure if those names are system specific though, definitely seems to be at least KDE specific.

Sorry, I am late to answer, my problem is solved with this permission

**Comment by axtloss** [comment]
I'll add the kde StatusNotifierItem permission to have it working on kde, but I'll keep this issue open for gnome support

**Comment by axtloss** [comment]
Oh I completely missed that, I'll fix it asap. thanks for letting me know!

**Comment by axtloss** [comment]
After some more research, I found [this issue](https://github.com/flathub/flatpak-builder-lint/issues/66), the flatpak build linter blocks me from changing the permission to be `--own-name=org.kde.StatusNotifierItem-3-1`.
It seems like the systray icon has to remain a broken feature for now

**Comment by vroger11** [comment]
> After some more research, I found [this issue](https://github.com/flathub/flatpak-builder-lint/issues/66), the flatpak build linter blocks me from changing the permission to be `--own-name=org.kde.StatusNotifierItem-3-1`. It seems like the systray icon has to remain a broken feature for now

Too bad this is not allowed, maybe add a temporary fix on the README for kde users?

**Comment by valeth** [comment]
@axtloss
 looked at the OBS Studio Flatpak definition and they seem to use `own-name` just fine.
 Also shows up when inspecting it with Flatseal.

https://github.com/obsproject/obs-studio/blob/ddba05c36cf89148533e4a2720154500560bc091/CI/flatpak/com.obsproject.Studio.json

**Comment by axtloss** [comment]
OBS doesn't go through the flathub build process, meaning they don't have to pass the flatpak linter checks, which is why they're able to use it

**Comment by aleksasiriski** [comment]
this also fixes the tray icon

https://github.com/SpacingBat3/WebCord/issues/328#issuecomment-1342837272

**Comment by axtloss** [comment]
I'd recommend trying the `owns` permission fix before completely downgrading and masking the package

**Comment by aleksasiriski** [comment]
> I'd recommend trying the `owns` permission fix before completely downgrading and masking the package

That fix is mainly for also broken Screen Share on Wayland, because of new Electron.

**Comment by Snaggly** [comment]
Hello, seems like this issue is still persisting. I can confirm that adding _org.kde.StatusNotifierItem-3-1_ to the "owns" section in FlatSeal also made the Webcord appindicator show up again under Plasma 5.26.4. However notification pop-ups do not show up still, when a new dm or message is being received.

**Comment by BenA0** [comment]
sway + waybar , arch 
running in wayland

adding `org.kde.StatusNotifierItem-3-1`  to owns doesn't fix iit.

**Comment by jtfen86** [comment]
Fedora 37, Budgie desktop, no tray icon no matter which tweak I try. Even org.kde.* to owns did nothing. I have my flatpaks installed as user if that matters.

**Comment by shuriken1812** [comment]
For me worked by adding org.kde.* in Owns using flatseal

**Comment by bbhtt** [comment]
Webcord now uses Electron 25 which should no longer require the workaround in the readme https://github.com/flathub/io.github.spacingbat3.webcord#fix-tray-icon due to this patch https://chromium-review.googlesource.com/c/chromium/src/+/4179380 (Included in Electron >=25, Chromium >=110.0.5481.77

Can you please test?

In my testing of Webcord and other apps for example Heroic, the `org.kde.StatusNotifierWatcher` also seems to be not required.

**Comment by aleksasiriski** [comment]
Works for me without `own-name=org.kde.*`

**Comment by bbhtt** [comment]
Thanks
