### ISSUE TITLE
UncaughtException: WebCord threw 'SyntaxError'

### ISSUE THREAD

**Issue by dusansimic** [flathub/io.github.spacingbat3.webcord#37]
The following error has occurred on startup on Arch Linux and Fedora Silverblue 37 (both flatpak packages and up to date).

![image](https://user-images.githubusercontent.com/12685466/216418098-05ce152d-228a-47f3-82d1-95bac26c8812.png)

When I run it through the command line I get the following output:
```
[10 preload-host-spawn-strategy] Warning: waitpid override ignores groups
[10 preload-host-spawn-strategy] Warning: waitpid override ignores groups
[3 preload-host-spawn-strategy] Warning: waitpid override ignores groups
[3 preload-host-spawn-strategy] Warning: waitpid override ignores groups
Gtk-Message: 19:32:19.687: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:32:19.688: Failed to load module "canberra-gtk-module"
```

**Comment by axtloss** [comment]
Please test the Appimage version of webcord to see if the issue persists there as this seems like an error in the webcord code, which I do not have control over.

**Comment by dusansimic** [comment]
AppImage seems to work fine, however I should mention that I've installed the flatpak package a few days ago and I've used it until it started spitting out this error. I've also had the issue before that (probably about a week ago) on Fedora Silverblue but I've just now reported it.

**Comment by axtloss** [comment]
It seems like this is an issue with webcord directly https://github.com/SpacingBat3/WebCord/issues/360 the workaround specified should work too, however the config file would be somewhere in  `~/.var/app/io.github.spacingbat3.webcord/`, I can't get the exact path currently.

**Comment by TheEvilSkeleton** [comment]
FWIW, this issue shouldn't happen anymore, as we implemented a workaround that automatically deletes `windowState` when it's 0 bytes https://github.com/flathub/io.github.spacingbat3.webcord/pull/38.

**Comment by dusansimic** [comment]
Thanks! I've updated the package on both machines now and will close the issue in a few days if it doesn't happen again.

**Comment by TheEvilSkeleton** [comment]
Can you keep it open for a month? Long-term testing would be more useful, as I'm not 100% sure if this workaround works.

**Comment by dusansimic** [comment]
Of course, not worries!
