### ISSUE TITLE
When streaming, red colors look like blue. Affects Flatpak version on Wayland only.

### ISSUE THREAD

**Issue by mak448a** [flathub/io.github.spacingbat3.webcord#39]
## Operating System / Platform
Linux
## Operating system architecture
x64 (64-bit Intel/AMD)

## Electron version

v22.0.0
## Application version

v4.1.1
## Bug description

When streaming in discord, if I look at a red picture on the stream, it displays as blue.
This bug is not reproduceable when running discord on Firefox.
## Additional context

This is in the FlatHub version only. I tested the AppImage and it didn't happen there.
I'm using Wayland on Fedora Linux, with KDE Plasma installed.
This doesn't occur when using X11.

**Comment by axtloss** [comment]
Did you test this on the non flatpak version of webcord? like the appimage for example

**Comment by axtloss** [comment]
You mentioned that discord on firefox doesn't have this issue, how is firefox installed? This could be an issue with flatpak or pipewire itself.

**Comment by axtloss** [comment]
Could you test discord from firefox then? I'm unable to reproduce the issue

**Comment by mak448a** [comment]
It doesn't have the issue either.

**Comment by axtloss** [comment]
are there any errors showing up when launching webcord from the terminal and launching a screen share?

**Comment by mak448a** [comment]
It looks like it's not happening anymore. Thanks for your time. I'm going to close this issue.
