### ISSUE TITLE
Wayland breaks webcord GUI

### ISSUE THREAD

**Issue by Xathros1** [flathub/io.github.spacingbat3.webcord#45]
Since this commit has been published 
https://github.com/flathub/io.github.spacingbat3.webcord/commit/72aed6d30138ed81c981a4f6fc728fca2be57bc3

- can't move the window anymore
- no way to maximize or minimize the window
- font-scaling is ignored (1.5) it's too small. 
- disabling wayland (via flatseal) outright crashes it

opensuse tumbleweed
Kernel: 6.3.2-1-default 
Resolution: 3840x2160
DE: GNOME 44.1
WM: Mutter

Screenshot of the window
![Bildschirmfoto vom 2023-05-27 21-52-33-obfuscated](https://github.com/flathub/io.github.spacingbat3.webcord/assets/72621668/e0e11ddf-1c7c-4ac2-b8b4-a77ee6d83645)

Log when running with default permissions:
```
cb@tumbleweed-pc:~> flatpak run io.github.spacingbat3.webcord 
[13 preload-host-spawn-strategy] Warning: waitpid override ignores groups
[13 preload-host-spawn-strategy] Warning: waitpid override ignores groups
[13 preload-host-spawn-strategy] Warning: waitpid override ignores groups
[6 preload-host-spawn-strategy] Warning: waitpid override ignores groups
[6 preload-host-spawn-strategy] Warning: waitpid override ignores groups
[6:0527/215620.400715:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
Cannot use import statement outside a module
[UPDATE] Anwendung ist aktuell!
```

Crash log when wayland disabled:
```
cb@tumbleweed-pc:~> flatpak run io.github.spacingbat3.webcord 
[13 preload-host-spawn-strategy] Warning: waitpid override ignores groups
[13 preload-host-spawn-strategy] Warning: waitpid override ignores groups
[13 preload-host-spawn-strategy] Warning: waitpid override ignores groups
[6 preload-host-spawn-strategy] Warning: waitpid override ignores groups
[6 preload-host-spawn-strategy] Warning: waitpid override ignores groups
[6:0527/220012.901529:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
The futex facility returned an unexpected error code.
/app/bin/run.sh: Zeile 18:     6 Abgebrochen             (Speicherabzug geschrieben) env TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-io.github.spacingbat3.webcord}" zypak-wrapper /app/bin/webcord/usr/bin/webcord $FLAGS "$@"
```

**Comment by axtloss** [comment]
Sadly there is not a lot I can do about this, WebCord in general is in a broken state and there appears to be a new issue when I fix an existing one.

My recommendation for now would be to use a different client until spacingbat3 finishes the WebCord rewrite and I update the flatpak to it

**Comment by Xathros1** [comment]
this maybe a issue with chromium imho. When you set it the flag there, Preferred Ozone platform to auto you get nearly the same broken result, albeit without the unmoveable window + no way to max+min but scaling is broken as well. 
I didn't had any such issues with the commit before you enabled wayland.

**Comment by Xathros1** [comment]
https://github.com/flathub/io.github.spacingbat3.webcord/commit/86ee8a1f9ab0b24f1bebadf07a34a50d3cce9ac6 
fixes upper titlebar (min/max) and unmoveable window
font scaling still broken

any way to fix this?

**Comment by axtloss** [comment]
Try running webcord with the `--force-device-scale-factor=2` argument, but replace the `2` with the scaling factor you use (200% = 2, 150% = 1.5)

**Comment by Xathros1** [comment]
> Try running webcord with the `--force-device-scale-factor=2` argument, but replace the `2` with the scaling factor you use (200% = 2, 150% = 1.5)

`flatpak run io.github.spacingbat3.webcord --force-device-scale-factor=2`

this breaks the window & it actually get's smaller
![Bildschirmfoto vom 2023-05-29 15-23-31](https://github.com/flathub/io.github.spacingbat3.webcord/assets/72621668/ba03f49b-1ee5-47cc-adb7-4aa04b71608a)

**Comment by axtloss** [comment]
If that does not work then there is not a lot I can do.
As I said before, the main WebCord branch is currently unmaintained and getting a rewrite which may fix some of these issues.

**Comment by dogtopus** [comment]
Also things like cursor size under mutter and HiDPI screen, IME support (Electron is still stuck at v1 protocol while everything uses v3). Pretty much completely broken like most other Electron apps under native Wayland.

**Comment by bbhtt** [comment]
Try `--enable-features=WaylandWindowDecorations` this was added in electron 17.x, webcord 4.2.0 uses electron 24.0.0, so it should work.

**Comment by Xathros1** [comment]
I just tried the appimage of webcord 4.3 and this seems to fix the scaling issue. it bumps electron to v25. Still to be released on flatpak.

**Comment by bbhtt** [comment]
Scaling is unrelated to flatpak. Did you try the appimage in native wayland ie. with `--ozone-platform-hint=auto`.

Scaling is wrong only in native wayland mode. In Xwayland or XOrg it works fine.

**Comment by Xathros1** [comment]
You're right, when enabling native wayland in the way you described, even with the appimage it **doesn't** scale correctly.

**Comment by axtloss** [comment]
You should get a new webcord update soon, once you have it run the command listed in https://github.com/flathub/io.github.spacingbat3.webcord/tree/opt-out-wayland#run-under-xwayland which would make webcord run under XWayland again and bring back proper scaling.

**Comment by Xathros1** [comment]
it's still not released
```
flatpak remote-info flathub io.github.spacingbat3.webcord
     Kennung: io.github.spacingbat3.webcord
         Ref: app/io.github.spacingbat3.webcord/x86_64/stable
 Architektur: x86_64
       Zweig: stable
    Sammlung: org.flathub.Stable
Herunterladen 100,8 MB
 Installiert: 254,1 MB
    Laufzeitumgebung: org.freedesktop.Platform/x86_64/22.08
         Sdk: org.freedesktop.Sdk/x86_64/22.08

      Commit: fd3fd654f6a9463a4f289f59af77a8414406c711c94c19c23b6a7cbb177f8a08
      Parent: 3456e73fb5e39dbf058a101d27467414f51baa9150dad89510d4c5a6da5985b4
     Betreff: Update webcord to 4.3.0 (e651cce5)
       Datum: 2023-06-24 13:34:12 +0000
```

**Comment by bbhtt** [comment]
The aarch64 build failed https://buildbot.flathub.org/#/builders/6/builds/49513 because resolving the screenshot url timed out for some reason.
