### ISSUE TITLE
No title bar

### ISSUE THREAD

**Issue by maxi0604** [flathub/io.github.spacingbat3.webcord#46]
There is no title bar on the Flatpak version but there is on the rpm version [here](https://github.com/SpacingBat3/WebCord/releases)

This issue occurs for me on Fedora Workstation 38, GNOME 44.2 with Wayland

**Comment by maxi0604** [comment]
Just realized this is a duplicate of #45

**Comment by Xathros1** [comment]
your issue should be fixed with the latest commit
