### ISSUE TITLE
Window cannot launch

### ISSUE THREAD

**Issue by bmhieserich** [flathub/io.github.spacingbat3.webcord#52]
It seems that on version 4.3.0 the app window will not display at all. The tray icon appears and can be interacted with, so the app itself can be launched and closed, the taskbar icon can also be interacted with, but no window appears. When running in terminal, I do notice the following lines appear that I believe are the source of the problem:
`[100:0624/132853.737615:FATAL:gpu_init.cc(495)] Passthrough is not supported, GL is egl, ANGLE is 
[GPU:5] crashed`
`[140:0624/132853.781459:FATAL:gpu_init.cc(495)] Passthrough is not supported, GL is egl, ANGLE is 
[GPU:5] crashed`
`[155:0624/132853.820937:FATAL:gpu_init.cc(495)] Passthrough is not supported, GL is egl, ANGLE is 
[GPU:5] crashed
`
The release notes on 4.3.0 did mention that the dependencies were updated to their latest versions, so I can imagine that some non-rolling-release distros in general may have issues with this if the dependencies are handled by the distro repos and do not update exactly to the latest versions. It's just my guess on what the issue is.

My own system's details:
KDE Neon 5.27
Plasma 5.27.6
Wayland
Kernel 5.19.0-45
GPU: AMD Radeon RX 6400

**Comment by axtloss** [comment]
Please try running a non-flatpak version of webcord from https://github.com/SpacingBat3/WebCord/releases/tag/v4.3.0 to see if it works there

**Comment by bmhieserich** [comment]
Version 4.3.0 does work running the .deb version. However, because this version is not hosted by Discover in KDE Neon (I did not see any sort of PPA or repo to add in the original project's page) I would still like to run the Flatpak to ensure it updates properly in the future.

Looks like the issue is unique to the Flatpak, or at least not in the .deb.

**Comment by axtloss** [comment]
Have you tried running it in xorg?

**Comment by bmhieserich** [comment]
It does run correctly in xorg, so the issue appears to be with the flatpak in Wayland, probably similar to or the same issue as the other currently open issue.

**Comment by axtloss** [comment]
You should get a new webcord update soon, once you have it run the command listed in https://github.com/flathub/io.github.spacingbat3.webcord/tree/opt-out-wayland#run-under-xwayland and webcord should work again.
