### ISSUE TITLE
v4.3.0 shows Need more input when attempting an update

### ISSUE THREAD

**Issue by aidzmtsk** [flathub/io.github.spacingbat3.webcord#53]
Getting this error when trying to update the application.
Any idea what this means?
![image](https://github.com/flathub/io.github.spacingbat3.webcord/assets/66116761/d2eb4189-2e46-4a2d-a4b4-2b9942162ea1)

_Originally posted by @aidzmtsk in https://github.com/flathub/io.github.spacingbat3.webcord/issues/50#issuecomment-1605804616_

**Comment by axtloss** [comment]
This is not an issue with webcord, it's a general known flatpak issue.
