### ISSUE TITLE
WebCord window blurry when using Wayland

### ISSUE THREAD

**Issue by mayhair** [flathub/io.github.spacingbat3.webcord#56]
When using WebCord via Wayland, the UI seems to be blurry. However, when configuring it to use X11 with Flatseal, the UI appears clear. This has been happening since the latest update, 4.3.0.

OS: Void Linux x86_64
Desktop environment: GNOME 44.2

Wayland UI:
![Screenshot from 2023-07-01 19-02-35](https://github.com/flathub/io.github.spacingbat3.webcord/assets/21954283/68ba8f93-fa62-40d9-925a-259d85227792)

X11 UI:
![Screenshot from 2023-07-01 19-03-13](https://github.com/flathub/io.github.spacingbat3.webcord/assets/21954283/28c1e756-0765-48c5-89d3-553641e4b546)

**Comment by axtloss** [comment]
This is not a webcord issue. It's more likely to be an issue with electron or something in your setup.
