### ISSUE TITLE
Wrong cursor

### ISSUE THREAD

**Issue by RaptaG** [flathub/io.github.spacingbat3.webcord#57]
the one displayed
![image](https://github.com/flathub/io.github.spacingbat3.webcord/assets/77157639/e8bdd3de-03f1-4529-91cd-b473c5e2dd01)

the one i use
![image](https://github.com/flathub/io.github.spacingbat3.webcord/assets/77157639/45282e95-fd16-4c98-97aa-c9addd5606c9)

happens on fedora kinoite 38 with wayland

**Comment by axtloss** [comment]
Not a webcord issue, you have to give flatpaks access to your cursor theme

**Comment by RaptaG** [comment]
@axtloss 
> Not a webcord issue, you have to give flatpaks access to your cursor theme

<br />

Which permission exactly? Other flatpaks work as intended.

**Comment by RaptaG** [comment]
Fixed it by allowing all Flatpaks to access the ~/.icons folder
