### ISSUE TITLE
Missing Window Decorations On GNOME 43.4 Wayland

### ISSUE THREAD

**Issue by TonyPrindel** [flathub/io.github.spacingbat3.webcord#58]
### Expected Behavior
WebCord should play well with GNOME's window decorations, particularly the exit button. This is the case with the AppImage version, which I newly downloaded from the official WebCord repo.

### Actual Behavior
For some reason, the FlatPak isn't playing nicely with GNOME's window decorations. The bar itself does not allow for the right-click context menu, and it is missing the exit button. Furthermore, the context feels quite clunky when switching between windowed and windowed fullscreen modes. I suspect this may be a clone of #45 and #46 but, contrary to the final posts on those issues, it is not yet resolved on my system.

### Steps to Reproduce the Problem
1. Open WebCord Flatpak under GNOME on Wayland.
2. Observe that the typical GNOME window decorations and functionality are not present.

### Specifications
Version: WebCord Flatpak 4.3.0
Platform: Debian 12
DE: GNOME 43.4 Wayland
CPU/GPU: AMD Ryzen 7 5700U with Radeon Graphics (using Mesa's graphics drivers)

Sample window (notice the lack of the typical exit button in the top right):
![image](https://github.com/flathub/io.github.spacingbat3.webcord/assets/22247701/69bed928-95ae-4acd-8b74-b18b249b123d)

Compared to the AppImage:
![image](https://github.com/flathub/io.github.spacingbat3.webcord/assets/22247701/78ce644c-a8fb-4b13-a679-91d97b1cf8a2)

**Comment by tobfos2611** [comment]
Same issue here on Fedora Silverblue 38

**Comment by axtloss** [comment]
As a temporary fix, while I figure out what the issue is, you can follow the instructions in https://github.com/flathub/io.github.spacingbat3.webcord#run-under-xwayland, which does show the buttons correctly.

**Comment by axtloss** [comment]
This is an issue with webcord directly, running the appimage with the same flags that the flatpak uses when using gnome wayland (`--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations`), the window does not have any controls.
