### ISSUE TITLE
Add wayland permission in Flatpak package

### ISSUE THREAD

**Issue by quantumde1** [flathub/io.github.spacingbat3.webcord#69]
### Description
Problem is:
WebCord not opening in Wayland session with ```--enable-features=UseOzonePlatform --ozone-platform=wayland``` flags with flatpak without ```flatpak override --user --socket=wayland io.github.spacingbat3.webcord```.

### Suggestions
Give a permission in Flatpak package.

### Alternatives
As non-secure method, you can use command which i show in description.

**Comment by axtloss** [comment]
This was done on purpose as WebCord on Wayland does not launch for some people #65 
The command you suggested or permanently giving WebCord access to Wayland is not any less secure than me changing it in the manifest.
