### ISSUE TITLE
Please add notes that Flatpaks aren't supported yet by WebCord.

### ISSUE THREAD

**Issue by SpacingBat3** [flathub/io.github.spacingbat3.webcord#7]
I've decided to open there an issue as WebCord's bug tracker reveives reports by Flatpak users that might be specific to Flatpak packaging. As I don't maintain this repo – I neither have a write access nor I find flatpak developments ready enough to be used with WebCord, at least with the current sandbox policy – I can't fix this issue and therefore it is pointless to report these in WebCord (they just bring me sometimes a confusion when I can't reproduce them and a bit more of unnecessary work).

It would be great to make it visible (e.g. in the description) that Flatpak sandbox is the reason of many breakages and many bugs aren't going to be the case with the native way of the packaging. To not confuse users, a recommendation should be made to test everything on the one of officially supported distributables before deciding if fill a bug in WebCord's bug tracker.

I might add some notes on templates on WebCord side as well.

Related:
- https://github.com/SpacingBat3/WebCord/issues/247
- https://github.com/SpacingBat3/WebCord/issues/158

**Comment by axtloss** [comment]
I'm very sorry that you had to deal with that, I completely forgot about adding any form of warning to the description.
I added a warning to the description in https://github.com/flathub/io.github.spacingbat3.webcord/commit/4384bd4dfb9a080263853372cb55fe88feed29ec, I hope that is enough.

**Comment by SpacingBat3** [comment]
> I'm very sorry that you had to deal with that, I completely forgot about adding any form of warning to the description. I added a warning to the description in [4384bd4](https://github.com/flathub/io.github.spacingbat3.webcord/commit/4384bd4dfb9a080263853372cb55fe88feed29ec), I hope that is enough.

I've also added a warning to the bug report template itself. That should stop some users from reporting the bugs before testing them on other distributables (it's quite generic, it doesn't just apply to Flatpaks).

I think that you should recommend to users they should switch to native or officially supported distributables and try to reproduce the bug there (rather than directly reporting it on this repo)  if you want to avoid users actually reporting bugs with WebCord, so the common Flatpak and other distributable errors would be reported on WebCord and Flatpak-specific issues would be reported there.

But yea, https://github.com/flathub/io.github.spacingbat3.webcord/commit/4384bd4dfb9a080263853372cb55fe88feed29ec resolves this. I'll close this issue...
