### ISSUE TITLE
Discord Rich Presence is not working

### ISSUE THREAD

**Issue by soredake** [flathub/io.github.spacingbat3.webcord#8]
Tested with this app https://github.com/flathub/md.obsidian.Obsidian, Discord Rich Presence works fine with proprietary flatpak'ed discord

**Comment by axtloss** [comment]
Have you tried with the non-flatpak webcord? If I remember correctly webcord doesn't support rich presence at all

**Comment by soredake** [comment]
Yes, you're right https://github.com/SpacingBat3/WebCord/discussions/58

I saw this code an though that it's supported https://github.com/flathub/io.github.spacingbat3.webcord/blob/master/vitamins/run.sh#L2-L7
