### ISSUE TITLE
Icon is a copy of official Discord icon

### ISSUE THREAD

**Issue by bbhtt** [flathub/io.github.spacingbat3.webcord#90]
We are tracking trademark violations and icons that are direct copies of other application's icons.

The current icon used here is direct copy of the official Discord icon with the colour changed which is not enough to make it distinct and avoid trademark issues/confusing people.

Please try to use your own icon for the application to avoid these issues. I think 2 months is a reasonable time period for us to wait for the icon to be changed.

You can find some resources for icon guidelines in https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines#app-icon

And the guidelines on trademarks https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines#no-trademark-violations

**Comment by bbhtt** [comment]
@axtloss Any update here? The two months is coming to an end...

**Comment by axtloss** [comment]
I am no longer a maintainer of the webcord package, @SpidFightFR would have to handle this

**Comment by SpidFightFR** [comment]
> We are tracking trademark violations and icons that are direct copies of other application's icons.
> 
> The current icon used here is direct copy of the official Discord icon with the colour changed which is not enough to make it distinct and avoid trademark issues/confusing people.
> 
> Please try to use your own icon for the application to avoid these issues. I think 2 months is a reasonable time period for us to wait for the icon to be changed.
> 
> You can find some resources for icon guidelines in https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines#app-icon
> 
> And the guidelines on trademarks https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines#no-trademark-violations

Hello. The icon used for the flatpak package (also findable in the vitamins folder) are the icons created by the [upstream webcord project](https://github.com/SpacingBat3/WebCord).

I only recently started to maintain a redistribution of that project. I do not take part in the visual identity of the upstream project not the designs related to it.

If the upstream project provide us a new icon that comforms with the demands stated above, then i would gladly update the vitamins content.

If you have any other questions regarding the visual identity of the webcord project, i recommend to ask on the upstream project instead.

I remain reachable in case of further questions.

Best regards - Spid.

**Comment by SpidFightFR** [comment]
@SpacingBat3 hey there. Hope you're doing great.
How should we deal with this?

**Comment by bbhtt** [comment]
> I think 2 months is a reasonable time period for us to wait for the icon to be changed.

The stipulated 2 months time was over on July 29. 

If this isn't solved, the app will be temporarily delisted, until this issue is fixed

**Comment by SpidFightFR** [comment]
> > I think 2 months is a reasonable time period for us to wait for the icon to be changed.
> 
> The stipulated 2 months time was over on July 29.
> 
> If this isn't solved, the app will be temporarily delisted, until this issue is fixed

Hey, hope you're doing good.

Look I'm gonna be honest, i don't really know what to answer to this.
Like said, I'm not much of a designer, and i didn't took the time to take into consideration the requirements for the logo of an app published on Flathub, and i don't want to rush out an icon, as i would find it to be an insult both for you, the maintainers of flathub, and @SpacingBat3.
I don't want to go off-track with the icon on the flathub.
And the webcord upstream project seems to be in maintenance mode for now.
Looks like I'm in a dead-end. And I also know what's gonna happen, I'm afraid...
Take care - Spid

**Comment by SpacingBat3** [comment]
@SpidFightFR @bbhtt unfortunately, I don't want to change the icon. The thing is, while the icon itself was inspired on somewhat Discord icon, it's not the recolorization of it. I've designed it from scratch and there is more than one difference if you compare both brandings.
The goal was obviously to make it look like Discord icon with some quirks but again this was greatly motivated with how the client is currently made and its dependence on `discord.com`. I've also belive that during the time I've switched the branding, there were people entirely opposing of concept of removing *Discord* word from the app name, and still want to distribute it with the icon from Discord. I'm personally oposed to that, I want from the icon to differ from Discord yet be close enough in some of the aspects so the users expect they'll get something that looks like official Dsicord client.
I should also say, the design of WebCord, including the icon, is close to what you can see in Caprine, as I used it as an example and followed its ideals when designing WebCord (I really liked it in the past, now it offers a bit worse experience due to Facebook greatly re-writting Messenger). Or even my design is a bit better, since I think their is quite similar to Messenger icon. If Caprine is not allowed to be hosted on Flatpak, I suppose WebCord will follow that as well.

**Comment by bbhtt** [comment]
Caprine has an issue open about icon too... It's not "allowed", if they don't change it too it will be delisted as well.

**Comment by SpacingBat3** [comment]
I see, maybe I should be more specific on some stuff:
- I'm not opposed to alternative icon designs, as long as I can accept the concept or idea of these.
- While WebCord is at *maintenance mode*, it doesn't mean I won't update it at all. The new features are still expected to be in the client, and some changes might happen. But I won't invest more of my time into time-sensitive tasks, especially when I consider to work more on a new client.
- The new client already has an icon design that doesn't include shapes similar to Discord's *trademark*, the only common thing it has are aesthetics in general, but those are found in many other clients logo designs as well (3 out of 4 mentioned clients feels like are doing this actually for their design). I guess the concept of that logo could be used to work on something in WebCord, although I doubt I want to invest my time at designing something for a client I want to eventually retire. I'm not sure if anyone wants to.
- I still find it too strong to call my icon just a *recolorization* (it kinda insults the time I took on drawing this with just my mouse, and toying with Inkspace 😄). Even the clyde shape doesn't remind anything of what you can find in both old and new Discord's designs (at least the ones I know, and it definitely wasn't purpose of the design.

**Comment by bbhtt** [comment]
Now, that you said, looking side by side I can identify the difference but that's hard to catch on a quick look and it does look a reskinned discord icon.

Anyway, I'll close this since it's not a copy.
